version: '3.9'

services:
  geoserver:
    image: kartoza/geoserver:${GS_VERSION}
    volumes:
      - geoserver-data:/opt/geoserver/data_dir
    ports:
      - ${GEOSERVER_PORT}:8080
    restart: on-failure
    environment:
      - GEOSERVER_DATA_DIR=${GEOSERVER_DATA_DIR}
      - GEOWEBCACHE_CACHE_DIR=${GEOWEBCACHE_CACHE_DIR}
      - GEOSERVER_ADMIN_PASSWORD=${GEOSERVER_ADMIN_PASSWORD}
      - GEOSERVER_ADMIN_USER=${GEOSERVER_ADMIN_USER}
      - INITIAL_MEMORY=${INITIAL_MEMORY}
      - MAXIMUM_MEMORY=${MAXIMUM_MEMORY}
      - STABLE_EXTENSIONS=${STABLE_EXTENSIONS}
      - COMMUNITY_EXTENSIONS=${COMMUNITY_EXTENSIONS}
      - GEOSERVER_CONTEXT_ROOT=${GEOSERVER_CONTEXT_ROOT}
    healthcheck:
      test: "curl --fail --silent --write-out 'HTTP CODE : %{http_code}

        ' --output /dev/null -u ${GEOSERVER_ADMIN_USER}:'${GEOSERVER_ADMIN_PASSWORD}' http://localhost:8080/geoserver/rest/about/version.xml"
      interval: 1m30s
      timeout: 10s
      retries: 3

volumes:
  geoserver-data:
    driver: azure_file
    driver_opts:
      share_name: gsfileshare
      storage_account_name: geoserverfileshare
      storage_account_key: sSdxSpnmhQKq3ZZmqa2B2l/17md1HPQNJBrFGPbfPU/WygWsD62U+QPODujjYbAFRbXVvIbK9vZi+ASt+IF+Vg==
      mount_options: dir_mode=0777,file_mode=0777
      file_share_path: /geoserver_data
